blank_issues_enabled: true
contact_links:
  - name: General help request
    url: https://support.pocketcasts.com/android/
    about: For general help requests, check the faq or get in touch with support.
